// solid/src/MyButton.tsx
import { createSignal } from 'solid-js'

interface MyButtonProps {
  type?: 'primary'
}

export function MyButton({ type }: MyButtonProps) {
  const [count, setCount] = createSignal(0)
  return (
    <button class="my-button" onClick={() => setCount(count() + 1)}>
      my button
      <br /> type: {type}
      <br /> count: {count()}
    </button>
  )
}

// vue/src/MyButton.vue
<script setup lang="ts">
import { ref } from 'vue'

const { type } = defineProps<{
  type?: 'primary'
}>()

const count = ref(0)
</script>

<template>
  <button class="my-button" @click="count++">
    my button<br />
    type: {{ type }}<br />
    count: {{ count }}
  </button>
</template>

<style scoped>
.my-button {
  padding: 8px 16px;
}
</style>
